# Header
menu:
  主页: /
  归档: /archives
  导航: /navigation
  作品: /demo
  关于: /about
# rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- archive
#- tag
- tagcloud
- links

# Miscellaneous
# google_analytics:
# favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
links:
  Soyaine's Blog: http://soyaine.github.io
  鸢尾: https://44021987.github.io